# Generated by Django 4.2.4 on 2023-09-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_done',
            new_name='is_completed',
        ),
    ]
