# Generated by Django 4.2.4 on 2023-09-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_is_done_todo_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
